# permissions for end users to view myreplicasets.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: myreplicaset-viewer-role
rules:
- apiGroups:
  - crd.k8s.demo
  resources:
  - myreplicasets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - crd.k8s.demo
  resources:
  - myreplicasets/status
  verbs:
  - get
