# permissions for end users to edit myreplicasets.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: myreplicaset-editor-role
rules:
- apiGroups:
  - crd.k8s.demo
  resources:
  - myreplicasets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - crd.k8s.demo
  resources:
  - myreplicasets/status
  verbs:
  - get
